repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: poetry run ruff check
        language: system
        args: [--fix]
        types: [python]
      - id: ruff-format
        name: Ruff format
        entry: poetry run ruff format
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
